[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "discord_mcp"
version = "0.1.0"
description = "Discord mcp"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "mcp>=1.12.3",
    "numpy>=2.3.2",
    "sqlite-vec>=0.1.7a2",
    "rapidfuzz>=3.13.0",
    "requests>=2.32.4",
    "pytest>=8.4.1",
    "fastapi>=0.116.1",
]

[project.scripts]
download-channels = "discord_downloader.download_channels:main"

[tool.pytest.ini_options]
markers = [
    "live: marks tests as requiring live Discord API access (deselect with '-m \"not live\"')"
]
addopts = "-m 'not live' -v"