[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "discord_mcp"
version = "0.1.0"
description = "Discord mcp"
dependencies = [
    "aiohttp>=3.8.0",
    "httpx>=0.24.0",
    "pytest>=7.0.0",
]

[project.scripts]
download-channels = "discord_downloader.download_channels:main"

[tool.pytest.ini_options]
markers = [
    "live: marks tests as requiring live Discord API access (deselect with '-m \"not live\"')"
]
addopts = "-m 'not live' -v"