[project]
name = "omni"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Koen van der Veen", email = "koenlennartvanderveen@gmail.com" },
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.104.1",
    "uvicorn[standard]>=0.24.0",
    "pydantic_settings",
    "requests",
    "numpy>=2.3.3",
    "sqlite-vec>=0.1.6",
    "toolbox_store>=0.1.1",
    "tqdm>=4.67.1",
    "apscheduler>=3.11.0",
    "browser-cookie3>=0.20.1",
    "playwright>=1.55.0",
    "cachetools>=6.2.0",
    "httpx==0.28.1",
    "rerankers[transformers] @ git+https://github.com/eelcovdw/rerankers.git@fix-colbert-query-mask",
    "anthropic>=0.68.1",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
