[project]
dependencies = [
    "cachetools>=6.1.0",
    "rapidfuzz==3.13.0",
    "fuzzywuzzy==0.18.0",
    "requests>=2.32.4",
    "uvicorn>=0.34.3",
    "fastapi>=0.115.13",
    "pydantic-settings>=2.10.0",
    "slack_sdk==3.35.0",
    "sqlite-vec==0.1.7a2",
    "numpy==2.3.2",
    "tqdm==4.67.1",
    "loguru==0.7.3",
    "mcp>=1.9.2",
    "fastsyftbox",
    "syft_core==0.2.8",
]

name = "slack_mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
fastsyftbox = { git = "https://github.com/OpenMined/fastsyftbox.git", rev = "fix-startup" }

[tool.uv]
dev-dependencies = [
    "pre-commit>=4.1.0",
    "pytest-xdist>=3.6.1",
    "pytest>=8.3.4",
    "typer==0.16.0",
]

[dependency-groups]
dev = ["pytest-xdist>=3.6.1", "pytest>=8.3.4"]
embeddings = ["torch>=2.2.2", "transformers>=4.54.0", "einops==0.8.1"]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true
disable_error_code = ["import-untyped"]

[tool.hatch.metadata]
allow-direct-references = true
