[project]
name = "broad-listening-ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Koen van der Veen", email = "koenlennartvanderveen@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
