repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
        always_run: true
      - id: trailing-whitespace
        always_run: true
        exclude: .bumpversion.cfg
      - id: check-docstring-first
        always_run: true
      - id: check-json
        always_run: true
      - id: check-yaml
        always_run: true
      - id: check-merge-conflict
        always_run: true
        args: ["--assume-in-merge"]
      - id: check-executables-have-shebangs
        always_run: true
      - id: debug-statements
        always_run: true
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.9
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
        types_or: [python, pyi] # TODO enable for jupyter
      - id: ruff-format
        types_or: [python, pyi] # TODO enable for jupyter

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/pre-commit/mirrors-prettier # This repository has been archived by the owner on Apr 11, 2024. It is now read-only.
    rev: "v3.0.0-alpha.9-for-vscode"
    hooks:
      - id: prettier
        exclude: \.min\.(js|css)$
